/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import dao.GradeDaoImpl;
import entities.Grade;
import entities.Profile;
import entities.StudentUnofficial;

/**
 *
 * @author USER
 */
public class DetailStudentUnOfficialForm extends javax.swing.JFrame {

    /**
     * Creates new form DetailStudentForm
     */
    public DetailStudentUnOfficialForm(StudentUnofficial student) {
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        initComponents();
        setData(student);
    }
    
    public void setData(StudentUnofficial student) {
        Profile profile = student.getProfile();
        emailTextFeild.setText(profile.getFullName());
        genderTextField.setText(String.valueOf(profile.isGender()));
        birthdayTextField.setText(profile.getDayOfBirth().toString());
        emailTextFeild.setText(profile.getEmail());
        phoneTextFeild.setText(profile.getPhoneNumber());
        idNumbertextField.setText(profile.getIdNumber());
        hometownTextField.setText(profile.getHomeTown());
        curentAddressTextField.setText(profile.getCurrentAddress());
        Grade grade = new GradeDaoImpl().getGrade(student.getIdRegisterCourse());
        registerGradeTextField.setText(grade.getNameGrade());
        registerTypeTextField.setText(student.getRegister().getType().toString());
        registerStatusTextField.setText(student.getRegister().getStatus().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lbStudentInfo = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        infPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        emailTextFeild = new javax.swing.JTextField();
        nameTextFeild1 = new javax.swing.JTextField();
        phoneTextFeild = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        idNumbertextField = new javax.swing.JTextField();
        idNumberLabel = new javax.swing.JLabel();
        hometownTextField = new javax.swing.JTextField();
        hometownAdressLabel = new javax.swing.JLabel();
        curentAddressTextField = new javax.swing.JTextField();
        curentAdressLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        birthdayTextField = new javax.swing.JTextField();
        registerPanel = new javax.swing.JPanel();
        registerGradeLabel = new javax.swing.JLabel();
        registerGradeTextField = new javax.swing.JTextField();
        regsiterStatusLabel = new javax.swing.JLabel();
        registerStatusTextField = new javax.swing.JTextField();
        regiaterTypeLabel = new javax.swing.JLabel();
        registerTypeTextField = new javax.swing.JTextField();
        DetailGradeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addToGradeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Details Student");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(820, 70));

        lbStudentInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbStudentInfo.setForeground(new java.awt.Color(0, 51, 153));
        lbStudentInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        lbStudentInfo.setText("INFORMATION UNOFFICIAL  STUDENT ");
        lbStudentInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lbStudentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbStudentInfo)
                .addContainerGap())
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        centerPanel.setLayout(new java.awt.BorderLayout());

        infPanel.setBackground(new java.awt.Color(204, 255, 255));
        infPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin"));
        infPanel.setPreferredSize(new java.awt.Dimension(366, 250));

        nameLabel.setBackground(new java.awt.Color(0, 51, 204));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Họ tên");

        emailLabel.setBackground(new java.awt.Color(0, 51, 204));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email");

        genderLabel.setBackground(new java.awt.Color(0, 51, 204));
        genderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderLabel.setText("Giới tính");

        nameTextFeild1.setRequestFocusEnabled(false);

        phoneLabel.setBackground(new java.awt.Color(0, 51, 204));
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setText("Phone");

        idNumberLabel.setBackground(new java.awt.Color(0, 51, 204));
        idNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idNumberLabel.setText("CMND");

        hometownAdressLabel.setBackground(new java.awt.Color(0, 51, 204));
        hometownAdressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hometownAdressLabel.setText("Quê quán");

        curentAdressLabel.setBackground(new java.awt.Color(0, 51, 204));
        curentAdressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curentAdressLabel.setText("Chỗ ở hiện tại");

        birthdayLabel.setBackground(new java.awt.Color(0, 51, 204));
        birthdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birthdayLabel.setText("Ngày sinh");

        javax.swing.GroupLayout infPanelLayout = new javax.swing.GroupLayout(infPanel);
        infPanel.setLayout(infPanelLayout);
        infPanelLayout.setHorizontalGroup(
            infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infPanelLayout.createSequentialGroup()
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infPanelLayout.createSequentialGroup()
                        .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(infPanelLayout.createSequentialGroup()
                                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(infPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGap(7, 7, 7)
                        .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infPanelLayout.createSequentialGroup()
                                .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(birthdayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                            .addComponent(emailTextFeild)
                            .addComponent(nameTextFeild1)))
                    .addGroup(infPanelLayout.createSequentialGroup()
                        .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hometownAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(curentAdressLabel)
                            .addComponent(idNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTextFeild)
                            .addComponent(idNumbertextField)
                            .addComponent(curentAddressTextField)
                            .addComponent(hometownTextField))))
                .addContainerGap())
        );
        infPanelLayout.setVerticalGroup(
            infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextFeild1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(birthdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idNumbertextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(idNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hometownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hometownAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curentAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curentAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        centerPanel.add(infPanel, java.awt.BorderLayout.LINE_START);

        registerPanel.setBackground(new java.awt.Color(255, 255, 204));
        registerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tình trạng đăng kí"));
        registerPanel.setPreferredSize(new java.awt.Dimension(365, 250));

        registerGradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerGradeLabel.setText("Lớp đăng kí");

        registerGradeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerGradeTextFieldActionPerformed(evt);
            }
        });

        regsiterStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regsiterStatusLabel.setText("Tình trạng đăng kí");

        regiaterTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regiaterTypeLabel.setText("Thể loại đăng kí");

        DetailGradeButton.setBackground(new java.awt.Color(255, 0, 255));
        DetailGradeButton.setForeground(new java.awt.Color(255, 255, 255));
        DetailGradeButton.setText("Tình trạng lớp học");

        deleteButton.setBackground(new java.awt.Color(255, 0, 51));
        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Hủy");

        addToGradeButton.setBackground(new java.awt.Color(0, 51, 204));
        addToGradeButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addToGradeButton.setForeground(new java.awt.Color(255, 255, 255));
        addToGradeButton.setText("Xếp vào lớp");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regsiterStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(regiaterTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addComponent(registerGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerGradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DetailGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(addToGradeButton)
                .addGap(91, 91, 91))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerGradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DetailGradeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerStatusTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(regsiterStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regiaterTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        centerPanel.add(registerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerGradeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerGradeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerGradeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DetailGradeButton;
    private javax.swing.JButton addToGradeButton;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthdayTextField;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField curentAddressTextField;
    private javax.swing.JLabel curentAdressLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextFeild;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel hometownAdressLabel;
    private javax.swing.JTextField hometownTextField;
    private javax.swing.JLabel idNumberLabel;
    private javax.swing.JTextField idNumbertextField;
    private javax.swing.JPanel infPanel;
    private javax.swing.JLabel lbStudentInfo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextFeild1;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextFeild;
    private javax.swing.JLabel regiaterTypeLabel;
    private javax.swing.JLabel registerGradeLabel;
    private javax.swing.JTextField registerGradeTextField;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField registerStatusTextField;
    private javax.swing.JTextField registerTypeTextField;
    private javax.swing.JLabel regsiterStatusLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
