/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import entities.StudentUnofficial;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import readFromExcelFile.ReadStudentUnofficicalFromExcelFile;
import service.StudentUnofficialService;
import service.StudentUnofficialServiceImpl;
import utils.FileUtils;
import utils.ImageUtils;

/**
 *
 * @author PC
 */
public class EnrollmentGradePlacementPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentGradePlacementPanel
     */
    public EnrollmentGradePlacementPanel() {
        initComponents();
        initEvens();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btUpdateData = new javax.swing.JButton();
        btAdmission = new javax.swing.JButton();
        btRegister = new javax.swing.JButton();
        btDivision = new javax.swing.JButton();
        lbBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btUpdateData.setBackground(new java.awt.Color(0, 153, 0));
        btUpdateData.setForeground(new java.awt.Color(255, 255, 255));
        btUpdateData.setText("Update data from excel online");
        btUpdateData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btUpdateData.setFocusPainted(false);
        add(btUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, 37));

        btAdmission.setBackground(new java.awt.Color(0, 0, 153));
        btAdmission.setForeground(new java.awt.Color(255, 255, 255));
        btAdmission.setText("Admissions source statistics");
        btAdmission.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAdmission.setFocusPainted(false);
        btAdmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmissionActionPerformed(evt);
            }
        });
        add(btAdmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 170, 37));

        btRegister.setBackground(new java.awt.Color(153, 51, 0));
        btRegister.setForeground(new java.awt.Color(255, 255, 255));
        btRegister.setText("Register form");
        btRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btRegister.setFocusPainted(false);
        add(btRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 149, 37));

        btDivision.setBackground(new java.awt.Color(255, 153, 0));
        btDivision.setForeground(new java.awt.Color(255, 255, 255));
        btDivision.setText("Grade division/arrange");
        btDivision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btDivision.setFocusPainted(false);
        add(btDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 223, 37));

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundEnrollment.jpg"))); // NOI18N
        add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btAdmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdmissionActionPerformed
    private void initEvens() {
        updateDataFromExcelOnlineButtonEvens();
        RegisterFormButtonEvents();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdmission;
    private javax.swing.JButton btDivision;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton btUpdateData;
    private javax.swing.JLabel lbBackground;
    // End of variables declaration//GEN-END:variables

    private void updateDataFromExcelOnlineButtonEvens() {
        btUpdateData.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                StudentUnofficialService stdUnOfficialService = new StudentUnofficialServiceImpl();
                List<StudentUnofficial> students = ReadStudentUnofficicalFromExcelFile.readStudentFromExcelFile(FileUtils.getPath("excels", "student.xlsx"));
                stdUnOfficialService.insertStudents(students);
                JOptionPane.showMessageDialog(EnrollmentGradePlacementPanel.this, "Update excel online successfully!", "Notification", JOptionPane.OK_OPTION, ImageUtils.loadImageIcon(getClass().getResource("/images/alarm.png").getPath()));
            }

        });

    }

    private void RegisterFormButtonEvents() {
        btRegister.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                RegisterForm registerForm = new RegisterForm();
                registerForm.setVisible(true);
            }

        });

    }
}
