/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import entities.Grade;
import entities.Teacher;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.io.FilenameUtils;
import service.GradeServiceImpl;
import service.TeacherServiceImpl;
import utils.FileUtils;
import utils.ImageUtils;
import utils.TimeUtils;

/**
 *
 * @author Mr.Chien
 */
public class GradeInformationForm extends javax.swing.JFrame {
    
    private final String[] EXT_FILE = {"png", "jpg", "jpeg", "gif"};
    private File selectedFile;
    private Grade grade;
    private Integer currentStudentQuantity;
    
    public GradeInformationForm(Grade grade, Integer currentStudentQuantity) {
        this.currentStudentQuantity = currentStudentQuantity;
        this.grade = grade;
        initComponents();
        setTextField();
        initEvent();
    }
    
    private void setTextField() {
        tfFullname.setText(grade.getNameGrade());
        tfCurrentStudentQuantity.setText(String.valueOf(currentStudentQuantity));
        studentQuantity1.setText(String.valueOf(grade.getStudentQuantity()));
        startTime.setText(grade.getStartTime().toString());
        endTime.setText(grade.getEndTime().toString());
        teacher.setText(grade.getTeacher().getIdTeacher() + " - " + grade.getTeacher().getProfileTeacher().getFullName());
        tfCurrentStudentQuantity.setEditable(false);
    }
    
    private void initEvent() {
        btUploadEvent();
        btSubmitEvent();
        showTeacherButtonEvents();
    }
    
    private void btSubmitEvent() {
        btSubmit.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                Teacher teacherSelected = new TeacherServiceImpl().getTeacher(teacher.getText());
                grade.setNameGrade(tfFullname.getText());
                grade.setTeacher(teacherSelected);
                grade.setStudentQuantity(Integer.parseInt(tfCurrentStudentQuantity.getText()));
                grade.setStartTime(TimeUtils.convertStringToLocalTime(startTime.getText()));
                grade.setEndTime(TimeUtils.convertStringToLocalTime(endTime.getText()));
                if (new GradeServiceImpl().updateGradeById(grade.getIdGrade(), grade)) {
                    JOptionPane.showMessageDialog(GradeInformationForm.this,
                            "This grade is updated successfully!!!", "Notification",
                            JOptionPane.OK_OPTION, ImageUtils.loadImageIcon(getClass().getResource("/images/alarm.png").getPath()));
                    setVisible(false);
                }
                
            }
        });
    }
    
    private void showTeacherButtonEvents() {
        showButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                TeacherForm teacherForm = new TeacherForm(teacher);
                teacherForm.setVisible(true);
            }
        });
    }
    
    private void btUploadEvent() {
        btUpload.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                JFileChooser fc = new JFileChooser(FileUtils.getPath("images", "python.jfif"));
                if (fc.showDialog(null, "Open") == JFileChooser.APPROVE_OPTION) {
                    selectedFile = fc.getSelectedFile();
                    final String ext = FilenameUtils.getExtension(selectedFile.getName());
                    if (Arrays.stream(EXT_FILE).anyMatch(t -> t.equalsIgnoreCase(ext))) {
                        lbAvatar.setIcon(ImageUtils.loadImageIcon(selectedFile.getPath(), 120, 150));
                    }
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrGender = new javax.swing.ButtonGroup();
        PnTop = new javax.swing.JPanel();
        lbStudentInfo = new javax.swing.JLabel();
        PnBottom = new javax.swing.JPanel();
        btSubmit = new javax.swing.JButton();
        PnCenter = new javax.swing.JPanel();
        pnCLeft = new javax.swing.JPanel();
        lbFullname = new javax.swing.JLabel();
        tfFullname = new javax.swing.JTextField();
        lbClassQuantity = new javax.swing.JLabel();
        lbStartDay = new javax.swing.JLabel();
        lbEndDay = new javax.swing.JLabel();
        tfCurrentStudentQuantity = new javax.swing.JTextField();
        lbCost = new javax.swing.JLabel();
        teacher = new javax.swing.JTextField();
        lbAvatar = new javax.swing.JLabel();
        btUpload = new javax.swing.JButton();
        endTime = new javax.swing.JTextField();
        startTime = new javax.swing.JTextField();
        studentQuantity1 = new javax.swing.JTextField();
        lbClassQuantity1 = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PnTop.setBackground(new java.awt.Color(255, 255, 255));
        PnTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbStudentInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbStudentInfo.setForeground(new java.awt.Color(0, 51, 153));
        lbStudentInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/course.png"))); // NOI18N
        lbStudentInfo.setText("Information Grade");
        lbStudentInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PnTop.add(lbStudentInfo);

        getContentPane().add(PnTop, java.awt.BorderLayout.PAGE_START);

        PnBottom.setBackground(new java.awt.Color(255, 255, 255));
        PnBottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        btSubmit.setBackground(new java.awt.Color(255, 51, 153));
        btSubmit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btSubmit.setText("Submit");
        btSubmit.setFocusPainted(false);
        PnBottom.add(btSubmit);

        getContentPane().add(PnBottom, java.awt.BorderLayout.PAGE_END);

        PnCenter.setBackground(new java.awt.Color(255, 255, 255));
        PnCenter.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true), javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204)))); // NOI18N
        PnCenter.setLayout(new java.awt.BorderLayout());

        pnCLeft.setBackground(new java.awt.Color(255, 204, 255));

        lbFullname.setText("Name: ");

        lbClassQuantity.setText("Current Student quantity: ");

        lbStartDay.setText("Start time:");

        lbEndDay.setText("End day:");

        lbCost.setText("Teacher:");

        lbAvatar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 0)));
        lbAvatar.setPreferredSize(new java.awt.Dimension(100, 100));

        btUpload.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        btUpload.setFocusPainted(false);

        lbClassQuantity1.setText("Student quantity: ");

        showButton.setText("Show Teacher");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCLeftLayout = new javax.swing.GroupLayout(pnCLeft);
        pnCLeft.setLayout(pnCLeftLayout);
        pnCLeftLayout.setHorizontalGroup(
            pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCLeftLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCLeftLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btUpload)))
                .addGap(58, 58, 58)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCLeftLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbClassQuantity)
                            .addComponent(lbFullname))
                        .addGap(60, 60, 60)
                        .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnCLeftLayout.createSequentialGroup()
                                .addGap(0, 77, Short.MAX_VALUE)
                                .addComponent(lbClassQuantity1)
                                .addGap(18, 18, 18)
                                .addComponent(studentQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))))
                    .addGroup(pnCLeftLayout.createSequentialGroup()
                        .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnCLeftLayout.createSequentialGroup()
                                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbEndDay)
                                    .addComponent(lbStartDay))
                                .addGap(60, 60, 60)
                                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(startTime)
                                        .addComponent(endTime, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                    .addComponent(tfCurrentStudentQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnCLeftLayout.createSequentialGroup()
                                .addComponent(lbCost, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(showButton)
                        .addContainerGap())))
        );

        pnCLeftLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbClassQuantity, lbCost, lbEndDay, lbFullname, lbStartDay});

        pnCLeftLayout.setVerticalGroup(
            pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCLeftLayout.createSequentialGroup()
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCLeftLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCLeftLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFullname)
                            .addComponent(tfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbClassQuantity)
                            .addComponent(studentQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbClassQuantity1)
                            .addComponent(tfCurrentStudentQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCLeftLayout.createSequentialGroup()
                        .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStartDay)
                            .addComponent(startTime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEndDay)))
                    .addComponent(btUpload))
                .addGap(30, 30, 30)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCost)
                    .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showButton)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        PnCenter.add(pnCLeft, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(PnCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnBottom;
    private javax.swing.JPanel PnCenter;
    private javax.swing.JPanel PnTop;
    private javax.swing.JButton btSubmit;
    private javax.swing.JButton btUpload;
    private javax.swing.ButtonGroup btgrGender;
    private javax.swing.JTextField endTime;
    private javax.swing.JLabel lbAvatar;
    private javax.swing.JLabel lbClassQuantity;
    private javax.swing.JLabel lbClassQuantity1;
    private javax.swing.JLabel lbCost;
    private javax.swing.JLabel lbEndDay;
    private javax.swing.JLabel lbFullname;
    private javax.swing.JLabel lbStartDay;
    private javax.swing.JLabel lbStudentInfo;
    private javax.swing.JPanel pnCLeft;
    private javax.swing.JButton showButton;
    private javax.swing.JTextField startTime;
    private javax.swing.JTextField studentQuantity1;
    private javax.swing.JTextField teacher;
    private javax.swing.JTextField tfCurrentStudentQuantity;
    private javax.swing.JTextField tfFullname;
    // End of variables declaration//GEN-END:variables
}
