/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

/**
 *
 * @author SMILE ^^
 */
public class HomepagePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public HomepagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNews3 = new java.awt.Panel();
        lbNews3 = new javax.swing.JLabel();
        panel7 = new java.awt.Panel();
        pnNews4 = new java.awt.Panel();
        lbNews4 = new javax.swing.JLabel();
        panel8 = new java.awt.Panel();
        pnNews5 = new java.awt.Panel();
        lbNews5 = new javax.swing.JLabel();
        panel9 = new java.awt.Panel();

        setLayout(new java.awt.GridLayout());

        pnNews3.setBackground(new java.awt.Color(255, 255, 255));
        pnNews3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbNews3.setBackground(new java.awt.Color(102, 153, 255));
        lbNews3.setText("News");

        panel7.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnNews3Layout = new javax.swing.GroupLayout(pnNews3);
        pnNews3.setLayout(pnNews3Layout);
        pnNews3Layout.setHorizontalGroup(
            pnNews3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNews3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbNews3)
                .addGap(69, 69, 69))
            .addGroup(pnNews3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNews3Layout.setVerticalGroup(
            pnNews3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNews3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNews3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnNews3);

        pnNews4.setBackground(new java.awt.Color(255, 255, 255));
        pnNews4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbNews4.setBackground(new java.awt.Color(102, 153, 255));
        lbNews4.setText("News");

        panel8.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnNews4Layout = new javax.swing.GroupLayout(pnNews4);
        pnNews4.setLayout(pnNews4Layout);
        pnNews4Layout.setHorizontalGroup(
            pnNews4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNews4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbNews4)
                .addGap(69, 69, 69))
            .addGroup(pnNews4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNews4Layout.setVerticalGroup(
            pnNews4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNews4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNews4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnNews4);

        pnNews5.setBackground(new java.awt.Color(255, 255, 255));
        pnNews5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbNews5.setBackground(new java.awt.Color(102, 153, 255));
        lbNews5.setText("News");

        panel9.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnNews5Layout = new javax.swing.GroupLayout(pnNews5);
        pnNews5.setLayout(pnNews5Layout);
        pnNews5Layout.setHorizontalGroup(
            pnNews5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNews5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbNews5)
                .addGap(69, 69, 69))
            .addGroup(pnNews5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNews5Layout.setVerticalGroup(
            pnNews5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNews5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNews5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnNews5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbNews3;
    private javax.swing.JLabel lbNews4;
    private javax.swing.JLabel lbNews5;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    private java.awt.Panel pnNews3;
    private java.awt.Panel pnNews4;
    private java.awt.Panel pnNews5;
    // End of variables declaration//GEN-END:variables
}
