/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import dao.CourseDao;
import dao.CourseDaoImpl;
import dao.GradeDao;
import dao.GradeDaoImpl;
import dao.StudentOfficialDao;
import dao.StudentOfficialDaoImpl;
import dao.TeacherDao;
import dao.TeacherDaoImpl;
import entities.Course;
import entities.Grade;
import entities.StudentOfficial;
import entities.Teacher;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import utils.ImageUtils;

/**
 *
 * @author SMILE ^^
 */
public class HomepagePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private CourseDao courseDao;
    private GradeDao gradeDao;
    private StudentOfficialDao studentOfficialDao;
    private TeacherDao teacherDao;
    private final Border separatePanelBorder = BorderFactory.createLineBorder(new Color(0, 0, 50), 1);

    public HomepagePanel() {
        initComponents();

        this.setOpaque(false);
        initPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCourse = new java.awt.Panel();
        lbCourse = new javax.swing.JLabel();
        pnCourseQty = new java.awt.Panel();
        lbCourseQty = new javax.swing.JLabel();
        courseSum = new javax.swing.JLabel();
        pnGrade = new java.awt.Panel();
        lbGrade = new javax.swing.JLabel();
        pnGradeQty = new java.awt.Panel();
        lbGradeQty = new javax.swing.JLabel();
        gradeSum = new javax.swing.JLabel();
        pnTeacher = new java.awt.Panel();
        lbTeacher = new javax.swing.JLabel();
        pnTeacherQty = new java.awt.Panel();
        lbTeacherQty = new javax.swing.JLabel();
        teacherSum = new javax.swing.JLabel();
        pnStudent = new java.awt.Panel();
        lbStudent = new javax.swing.JLabel();
        pnStudentQty = new java.awt.Panel();
        lbStudentQty = new javax.swing.JLabel();
        studentSum = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1560, 100));
        setLayout(new java.awt.GridLayout(1, 4));

        pnCourse.setBackground(new java.awt.Color(255, 255, 255));
        pnCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnCourse.setPreferredSize(new java.awt.Dimension(376, 100));

        lbCourse.setBackground(new java.awt.Color(102, 153, 255));
        lbCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courseManager.png"))); // NOI18N
        lbCourse.setText("COURSES");
        pnCourse.add(lbCourse);

        pnCourseQty.setBackground(new java.awt.Color(153, 204, 255));
        pnCourseQty.setPreferredSize(new java.awt.Dimension(255, 255));

        lbCourseQty.setBackground(new java.awt.Color(255, 255, 255));
        lbCourseQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbCourseQty.setText("Number of courses: ");

        courseSum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        courseSum.setText("jLabel1");

        javax.swing.GroupLayout pnCourseQtyLayout = new javax.swing.GroupLayout(pnCourseQty);
        pnCourseQty.setLayout(pnCourseQtyLayout);
        pnCourseQtyLayout.setHorizontalGroup(
            pnCourseQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCourseQtyLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(courseSum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnCourseQtyLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbCourseQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCourseQtyLayout.setVerticalGroup(
            pnCourseQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCourseQtyLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbCourseQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseSum)
                .addGap(192, 192, 192))
        );

        pnCourse.add(pnCourseQty);

        add(pnCourse);

        pnGrade.setBackground(new java.awt.Color(255, 255, 255));
        pnGrade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbGrade.setBackground(new java.awt.Color(102, 153, 255));
        lbGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grade.jpg"))); // NOI18N
        lbGrade.setText("GRADES");
        pnGrade.add(lbGrade);

        pnGradeQty.setBackground(new java.awt.Color(206, 230, 255));
        pnGradeQty.setPreferredSize(new java.awt.Dimension(255, 255));

        lbGradeQty.setBackground(new java.awt.Color(255, 255, 255));
        lbGradeQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbGradeQty.setText("Number of grades: ");

        gradeSum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        gradeSum.setText("jLabel2");

        javax.swing.GroupLayout pnGradeQtyLayout = new javax.swing.GroupLayout(pnGradeQty);
        pnGradeQty.setLayout(pnGradeQtyLayout);
        pnGradeQtyLayout.setHorizontalGroup(
            pnGradeQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGradeQtyLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(gradeSum)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(pnGradeQtyLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbGradeQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnGradeQtyLayout.setVerticalGroup(
            pnGradeQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGradeQtyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbGradeQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradeSum)
                .addGap(193, 193, 193))
        );

        pnGrade.add(pnGradeQty);

        add(pnGrade);

        pnTeacher.setBackground(new java.awt.Color(255, 255, 255));
        pnTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbTeacher.setBackground(new java.awt.Color(102, 153, 255));
        lbTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacherManager.png"))); // NOI18N
        lbTeacher.setText("TEACHERS");
        lbTeacher.setMaximumSize(new java.awt.Dimension(120, 50));
        lbTeacher.setMinimumSize(new java.awt.Dimension(120, 50));
        lbTeacher.setPreferredSize(new java.awt.Dimension(120, 50));
        pnTeacher.add(lbTeacher);

        pnTeacherQty.setBackground(new java.awt.Color(153, 204, 255));
        pnTeacherQty.setPreferredSize(new java.awt.Dimension(255, 255));

        lbTeacherQty.setBackground(new java.awt.Color(255, 255, 255));
        lbTeacherQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTeacherQty.setText("Number of teachers: ");

        teacherSum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        teacherSum.setText("jLabel4");

        javax.swing.GroupLayout pnTeacherQtyLayout = new javax.swing.GroupLayout(pnTeacherQty);
        pnTeacherQty.setLayout(pnTeacherQtyLayout);
        pnTeacherQtyLayout.setHorizontalGroup(
            pnTeacherQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTeacherQtyLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(teacherSum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnTeacherQtyLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbTeacherQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTeacherQtyLayout.setVerticalGroup(
            pnTeacherQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTeacherQtyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTeacherQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherSum)
                .addGap(193, 193, 193))
        );

        pnTeacher.add(pnTeacherQty);

        add(pnTeacher);

        pnStudent.setBackground(new java.awt.Color(255, 255, 255));
        pnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbStudent.setBackground(new java.awt.Color(102, 153, 255));
        lbStudent.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentManager.png"))); // NOI18N
        lbStudent.setText("STUDENTS");
        lbStudent.setMaximumSize(new java.awt.Dimension(120, 50));
        lbStudent.setMinimumSize(new java.awt.Dimension(120, 50));
        lbStudent.setPreferredSize(new java.awt.Dimension(120, 50));
        pnStudent.add(lbStudent);

        pnStudentQty.setBackground(new java.awt.Color(206, 230, 255));
        pnStudentQty.setPreferredSize(new java.awt.Dimension(255, 255));

        lbStudentQty.setBackground(new java.awt.Color(255, 255, 255));
        lbStudentQty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStudentQty.setText("Number of students: ");

        studentSum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        studentSum.setText("jLabel3");

        javax.swing.GroupLayout pnStudentQtyLayout = new javax.swing.GroupLayout(pnStudentQty);
        pnStudentQty.setLayout(pnStudentQtyLayout);
        pnStudentQtyLayout.setHorizontalGroup(
            pnStudentQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStudentQtyLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(studentSum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnStudentQtyLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbStudentQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnStudentQtyLayout.setVerticalGroup(
            pnStudentQtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStudentQtyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbStudentQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSum)
                .addGap(193, 193, 193))
        );

        pnStudent.add(pnStudentQty);

        add(pnStudent);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseSum;
    private javax.swing.JLabel gradeSum;
    private javax.swing.JLabel lbCourse;
    private javax.swing.JLabel lbCourseQty;
    private javax.swing.JLabel lbGrade;
    private javax.swing.JLabel lbGradeQty;
    private javax.swing.JLabel lbStudent;
    private javax.swing.JLabel lbStudentQty;
    private javax.swing.JLabel lbTeacher;
    private javax.swing.JLabel lbTeacherQty;
    private java.awt.Panel pnCourse;
    private java.awt.Panel pnCourseQty;
    private java.awt.Panel pnGrade;
    private java.awt.Panel pnGradeQty;
    private java.awt.Panel pnStudent;
    private java.awt.Panel pnStudentQty;
    private java.awt.Panel pnTeacher;
    private java.awt.Panel pnTeacherQty;
    private javax.swing.JLabel studentSum;
    private javax.swing.JLabel teacherSum;
    // End of variables declaration//GEN-END:variables

    private void initPanels() {
        courseDao = new CourseDaoImpl();
        List<Course> courses = courseDao.getAll();
        gradeDao = new GradeDaoImpl();
        List<Grade> grades = gradeDao.getAll();
        studentOfficialDao = new StudentOfficialDaoImpl();
        List<StudentOfficial> studentOfficials = studentOfficialDao.getAll();
        teacherDao = new TeacherDaoImpl();
        List<Teacher> teachers = teacherDao.getAll();

        courseSum.setText(String.valueOf(courses.size()));
        gradeSum.setText(String.valueOf(grades.size()));
        studentSum.setText(String.valueOf(studentOfficials.size()));
        teacherSum.setText(String.valueOf(teachers.size()));
    }

//    @Override
//    protected void paintComponent(Graphics g) {
//        Image image = ImageUtils.load(getClass().getResource("/images/HomepageBg.jpg").getPath());
//        g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
//        super.paintComponent(g);
//
//    }

    @Override
    public void paintComponents(Graphics g) {
        super.paintComponents(g); //To change body of generated methods, choose Tools | Templates.
    }

}
