/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub;

import entities.Grade;

/**
 *
 * @author qphan
 */
public class PnStudent extends javax.swing.JPanel {

    public PnStudent() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrGender = new javax.swing.ButtonGroup();
        PnTop = new javax.swing.JPanel();
        lbStudentInfo = new javax.swing.JLabel();
        PnCenter = new javax.swing.JPanel();
        spCenter = new javax.swing.JSplitPane();
        pnCLeft = new javax.swing.JPanel();
        lbFullname = new javax.swing.JLabel();
        tfFullname = new javax.swing.JTextField();
        cbbGrade = new javax.swing.JComboBox<>();
        lbGrade = new javax.swing.JLabel();
        lbGrade1 = new javax.swing.JLabel();
        tfFullname1 = new javax.swing.JTextField();
        lbFullname1 = new javax.swing.JLabel();
        tfFullname2 = new javax.swing.JTextField();
        lbFullname2 = new javax.swing.JLabel();
        tfFullname3 = new javax.swing.JTextField();
        lbFullname3 = new javax.swing.JLabel();
        tfFullname4 = new javax.swing.JTextField();
        lbFullname4 = new javax.swing.JLabel();
        tfFullname5 = new javax.swing.JTextField();
        lbFullname5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnCRight = new javax.swing.JPanel();
        lbLiter = new javax.swing.JLabel();
        tfMath = new javax.swing.JTextField();
        tfLiter = new javax.swing.JTextField();
        lbMath = new javax.swing.JLabel();
        scrollInfo = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JTextArea();
        lbLiter1 = new javax.swing.JLabel();
        lbLiter3 = new javax.swing.JLabel();
        scrollInfo1 = new javax.swing.JScrollPane();
        taInfo1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        lbStudentInfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbStudentInfo.setForeground(new java.awt.Color(0, 51, 153));
        lbStudentInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        lbStudentInfo.setText("THÔNG TIN HỌC VIÊN");
        lbStudentInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PnTop.add(lbStudentInfo);

        add(PnTop, java.awt.BorderLayout.PAGE_START);

        PnCenter.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 0, 204)))); // NOI18N
        PnCenter.setLayout(null);

        spCenter.setOneTouchExpandable(true);

        pnCLeft.setBackground(new java.awt.Color(204, 255, 255));

        lbFullname.setText("Họ tên:");

        lbGrade.setText("Lớp:");

        lbGrade1.setText("Giới tính:");

        lbFullname1.setText("Email");

        lbFullname2.setText("Phone number");

        lbFullname3.setText("IdNumber");

        lbFullname4.setText("Hometown");

        lbFullname5.setText("Current Address");

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Birthday");

        jLabel3.setBackground(new java.awt.Color(255, 0, 51));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnCLeftLayout = new javax.swing.GroupLayout(pnCLeft);
        pnCLeft.setLayout(pnCLeftLayout);
        pnCLeftLayout.setHorizontalGroup(
            pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFullname)
                    .addComponent(lbGrade)
                    .addComponent(lbGrade1)
                    .addComponent(lbFullname1)
                    .addComponent(lbFullname2)
                    .addComponent(lbFullname3)
                    .addComponent(lbFullname4)
                    .addComponent(lbFullname5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFullname5)
                    .addComponent(tfFullname4)
                    .addComponent(tfFullname3)
                    .addComponent(tfFullname2)
                    .addComponent(tfFullname1)
                    .addComponent(tfFullname)
                    .addComponent(cbbGrade, 0, 253, Short.MAX_VALUE)
                    .addGroup(pnCLeftLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnCLeftLayout.setVerticalGroup(
            pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCLeftLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFullname)
                    .addComponent(tfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbGrade)
                    .addComponent(cbbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGrade1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFullname1)
                    .addComponent(tfFullname1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFullname2)
                    .addComponent(tfFullname2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFullname3)
                    .addComponent(tfFullname3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFullname4)
                    .addComponent(tfFullname4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFullname5)
                    .addComponent(tfFullname5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pnCLeftLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbGrade, tfFullname});

        spCenter.setLeftComponent(pnCLeft);

        pnCRight.setBackground(new java.awt.Color(255, 255, 204));
        pnCRight.setMinimumSize(new java.awt.Dimension(340, 100));

        lbLiter.setText("Điểm thực hành:");

        tfMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMathActionPerformed(evt);
            }
        });

        lbMath.setText("Điểm lí thyết:");

        taInfo.setColumns(20);
        taInfo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        taInfo.setForeground(new java.awt.Color(51, 0, 204));
        taInfo.setLineWrap(true);
        taInfo.setRows(5);
        taInfo.setTabSize(4);
        taInfo.setWrapStyleWord(true);
        scrollInfo.setViewportView(taInfo);

        lbLiter1.setText("Khen thường:");

        lbLiter3.setText("Kỷ luật:");

        taInfo1.setColumns(20);
        taInfo1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        taInfo1.setForeground(new java.awt.Color(51, 0, 204));
        taInfo1.setLineWrap(true);
        taInfo1.setRows(5);
        taInfo1.setTabSize(4);
        taInfo1.setWrapStyleWord(true);
        scrollInfo1.setViewportView(taInfo1);

        javax.swing.GroupLayout pnCRightLayout = new javax.swing.GroupLayout(pnCRight);
        pnCRight.setLayout(pnCRightLayout);
        pnCRightLayout.setHorizontalGroup(
            pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCRightLayout.createSequentialGroup()
                        .addGroup(pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMath)
                            .addComponent(lbLiter)
                            .addComponent(lbLiter1))
                        .addGap(40, 40, 40)
                        .addGroup(pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMath)
                            .addComponent(tfLiter)
                            .addComponent(scrollInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))
                    .addGroup(pnCRightLayout.createSequentialGroup()
                        .addComponent(lbLiter3)
                        .addGap(54, 54, 54)
                        .addComponent(scrollInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnCRightLayout.setVerticalGroup(
            pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMath)
                    .addComponent(tfMath, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbLiter)
                    .addComponent(tfLiter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCRightLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(scrollInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCRightLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbLiter1)))
                .addGroup(pnCRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCRightLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbLiter3))
                    .addGroup(pnCRightLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(scrollInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        spCenter.setRightComponent(pnCRight);

        PnCenter.add(spCenter);
        spCenter.setBounds(16, 29, 768, 546);

        add(PnCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMathActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnCenter;
    private javax.swing.JPanel PnTop;
    private javax.swing.ButtonGroup btgrGender;
    private javax.swing.JComboBox<Grade> cbbGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbFullname;
    private javax.swing.JLabel lbFullname1;
    private javax.swing.JLabel lbFullname2;
    private javax.swing.JLabel lbFullname3;
    private javax.swing.JLabel lbFullname4;
    private javax.swing.JLabel lbFullname5;
    private javax.swing.JLabel lbGrade;
    private javax.swing.JLabel lbGrade1;
    private javax.swing.JLabel lbLiter;
    private javax.swing.JLabel lbLiter1;
    private javax.swing.JLabel lbLiter3;
    private javax.swing.JLabel lbMath;
    private javax.swing.JLabel lbStudentInfo;
    private javax.swing.JPanel pnCLeft;
    private javax.swing.JPanel pnCRight;
    private javax.swing.JScrollPane scrollInfo;
    private javax.swing.JScrollPane scrollInfo1;
    private javax.swing.JSplitPane spCenter;
    private javax.swing.JTextArea taInfo;
    private javax.swing.JTextArea taInfo1;
    private javax.swing.JTextField tfFullname;
    private javax.swing.JTextField tfFullname1;
    private javax.swing.JTextField tfFullname2;
    private javax.swing.JTextField tfFullname3;
    private javax.swing.JTextField tfFullname4;
    private javax.swing.JTextField tfFullname5;
    private javax.swing.JTextField tfLiter;
    private javax.swing.JTextField tfMath;
    // End of variables declaration//GEN-END:variables
}
